### ISSUE TITLE
Add combined world player count

### ISSUE THREAD

**Issue by Johnsonk79** [xXKHaLeD098Xx/WorldPlayerCount#4]
Maybe add multiple world support for games like skywars and bedwars? example: count bw1&bw2 to show the two world's players added together?

**Comment by xXKHaLeD098Xx** [comment]
Feature considered, i'll add it when i can

**Comment by AbisGameryt** [comment]
Anyway that this can be added to skyblock? All skyblock island names start with sb so maybe add a option for that. It has to count all worlds that start with "sb". It may seem hard but it definatly isn't.

**Comment by xXKHaLeD098Xx** [comment]
> Anyway that this can be added to skyblock? All skyblock island names start with sb so maybe add a option for that. It has to count all worlds that start with "sb". It may seem hard but it definatly isn't.

Please make a separate issue for this, Combined World Player Count feature has been added and i'm closing this issue
