### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by UnEnanoMas** [xXKHaLeD098Xx/WorldPlayerCount#5]
![Captura de pantalla (67)](https://user-images.githubusercontent.com/63286108/84573888-82907080-ada3-11ea-93f7-3b43665121e0.png)

I have copied the text well, the name of the world is also fine, I put it and it does not work, I have also tried restarting it and nothing.

**Comment by xXKHaLeD098Xx** [comment]
@UnEnanoMas Hello, as i understand in your screenshot you are trying to change the slapper's name
NOTE: This plugin ONLY works when CREATING the slapper not editing it
please try removing the slapper and re-creating it with the right format as above

**Comment by UnEnanoMas** [comment]
Oh yes it works now ty

**Comment by xXKHaLeD098Xx** [comment]
No problem happy to help, closing the issue now.
